"""create maintenance table

Revision ID: ab38bb3a0a91
Revises: b2612a71eac3
Create Date: 2026-07-12 15:13:23.393620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab38bb3a0a91'
down_revision: Union[str, Sequence[str], None] = 'b2612a71eac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'OIL_CHANGE', 'TIRE_CHANGE', name='maintenance_type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenance_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    # ### end Alembic commands ###
