"""create vehicles table

Revision ID: ca04279d1870
Revises: cc4c6ac2b985
Create Date: 2026-07-12 12:19:37.399398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca04279d1870'
down_revision: Union[str, Sequence[str], None] = 'cc4c6ac2b985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('TRUCK', 'VAN', 'CAR', 'MOTORCYCLE', name='vehicle_type'), nullable=False),
    sa.Column('max_load_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'IN_SHOP', 'RETIRED', name='vehicle_status'), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
